global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http.Features;
global using Microsoft.AspNetCore.HttpOverrides;
global using Microsoft.AspNetCore.ResponseCompression;
global using Microsoft.AspNetCore.StaticFiles;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.FileProviders;
global using Microsoft.Extensions.FileProviders.Physical;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Http;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Primitives;
global using Microsoft.Net.Http.Headers;
global using System.Buffers;
global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Formats.Asn1;
global using System.Formats.Dns;
global using System.Globalization;
global using System.IO.Compression;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Net.NetworkInformation;
global using System.Net.Sockets;
global using System.Net.WebSockets;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Security.Cryptography;
global using System.Security.Cryptography.X509Certificates;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Threading.Channels;
global using static Microsoft.AspNetCore.Http.StatusCodes;
global using static System.Buffers.Binary.BinaryPrimitives;
global using static System.Net.Http.HttpCompletionOption;
global using static System.StringComparison;
global using static System.StringSplitOptions;
global using static System.Text.RegularExpressions.RegexOptions;
global using CacheControlHeaderValue = Microsoft.Net.Http.Headers.CacheControlHeaderValue;
